
export const MessageType = {
    TEXT: 'TEXT',
    IMAGE: 'IMAGE',
    FILE: 'FILE',
    EMOJI: 'EMOJI'
};

export const SessionType = {
    CHAT: 'CHAT',
    GROUPCHAT: 'GROUPCHAT'
};

export const EmojiClassic = {
    '[微笑]': ['微笑', '[微笑]', '/static/emoji/Expression_1.png'],
    '[撇嘴]': ['撇嘴', '[撇嘴]', '/static/emoji/Expression_2.png'],
    '[色]': ['色', '[色]', '/static/emoji/Expression_3.png'],
    '[发呆]': ['发呆', '[发呆]', '/static/emoji/Expression_4.png'],
    '[得意]': ['得意', '[得意]', '/static/emoji/Expression_5.png'],
    '[大哭]': ['大哭', '[大哭]', '/static/emoji/Expression_6.png'],
    '[害羞]': ['害羞', '[害羞]', '/static/emoji/Expression_7.png'],
    '[闭嘴]': ['闭嘴', '[闭嘴]', '/static/emoji/Expression_8.png'],
    '[睡]': ['睡', '[睡]', '/static/emoji/Expression_9.png'],
    '[流泪]': ['流泪', '[流泪]', '/static/emoji/Expression_10.png'],
    '[尴尬]': ['尴尬', '[尴尬]', '/static/emoji/Expression_11.png'],
    '[发怒]': ['发怒', '[发怒]', '/static/emoji/Expression_12.png'],
    '[调皮]': ['调皮', '[调皮]', '/static/emoji/Expression_13.png'],
    '[呲牙]': ['呲牙', '[呲牙]', '/static/emoji/Expression_14.png'],
    '[惊讶]': ['惊讶', '[惊讶]', '/static/emoji/Expression_15.png'],
    '[难过]': ['难过', '[难过]', '/static/emoji/Expression_16.png'],
    '[酷]': ['酷', '[酷]', '/static/emoji/Expression_17.png'],
    '[冷汗]': ['冷汗', '[冷汗]', '/static/emoji/Expression_18.png'],
    '[抓狂]': ['抓狂', '[抓狂]', '/static/emoji/Expression_19.png'],
    '[吐]': ['吐', '[吐]', '/static/emoji/Expression_20.png'],
    '[偷笑]': ['偷笑', '[偷笑]', '/static/emoji/Expression_21.png'],
    '[愉快]': ['愉快', '[愉快]', '/static/emoji/Expression_22.png'],
    '[白眼]': ['白眼', '[白眼]', '/static/emoji/Expression_23.png'],
    '[傲慢]': ['傲慢', '[傲慢]', '/static/emoji/Expression_24.png'],
    '[饥饿]': ['饥饿', '[饥饿]', '/static/emoji/Expression_25.png'],
    '[困]': ['困', '[困]', '/static/emoji/Expression_26.png'],
    '[惊恐]': ['惊恐', '[惊恐]', '/static/emoji/Expression_27.png'],
    '[流汗]': ['流汗', '[流汗]', '/static/emoji/Expression_28.png'],
    '[憨笑]': ['憨笑', '[憨笑]', '/static/emoji/Expression_29.png'],
    '[悠闲]': ['悠闲', '[悠闲]', '/static/emoji/Expression_30.png'],
    '[奋斗]': ['奋斗', '[奋斗]', '/static/emoji/Expression_31.png'],
    '[咒骂]': ['咒骂', '[咒骂]', '/static/emoji/Expression_32.png'],
    '[疑问]': ['疑问', '[疑问]', '/static/emoji/Expression_33.png'],
    '[嘘]': ['嘘', '[嘘]', '/static/emoji/Expression_34.png'],
    '[晕]': ['晕', '[晕]', '/static/emoji/Expression_35.png'],
    '[抓狂]': ['抓狂', '[抓狂]', '/static/emoji/Expression_36.png'],
    '[衰]': ['衰', '[衰]', '/static/emoji/Expression_37.png'],
    '[骷髅]': ['骷髅', '[骷髅]', '/static/emoji/Expression_38.png'],
    '[敲打]': ['敲打', '[敲打]', '/static/emoji/Expression_39.png'],
    '[再见]': ['再见', '[再见]', '/static/emoji/Expression_40.png'],
    '[擦汗]': ['擦汗', '[擦汗]', '/static/emoji/Expression_41.png'],
    '[抠鼻]': ['抠鼻', '[抠鼻]', '/static/emoji/Expression_42.png'],
    '[鼓掌]': ['鼓掌', '[鼓掌]', '/static/emoji/Expression_43.png'],
    '[糗大了]': ['糗大了', '[糗大了]', '/static/emoji/Expression_44.png'],
    '[坏笑]': ['坏笑', '[坏笑]', '/static/emoji/Expression_45.png'],
    '[左哼哼]': ['左哼哼', '[左哼哼]', '/static/emoji/Expression_46.png'],
    '[右哼哼]': ['右哼哼', '[右哼哼]', '/static/emoji/Expression_47.png'],
    '[哈欠]': ['哈欠', '[哈欠]', '/static/emoji/Expression_48.png'],
    '[鄙视]': ['鄙视', '[鄙视]', '/static/emoji/Expression_49.png'],
    '[委屈]': ['委屈', '[委屈]', '/static/emoji/Expression_50.png'],
    '[快哭了]': ['快哭了', '[快哭了]', '/static/emoji/Expression_51.png'],
    '[阴险]': ['阴险', '[阴险]', '/static/emoji/Expression_52.png'],
    '[亲亲]': ['亲亲', '[亲亲]', '/static/emoji/Expression_53.png'],
    '[吓]': ['吓', '[吓]', '/static/emoji/Expression_54.png'],
    '[可怜]': ['可怜', '[可怜]', '/static/emoji/Expression_55.png'],
    '[菜刀]': ['菜刀', '[菜刀]', '/static/emoji/Expression_56.png'],
    '[西瓜]': ['西瓜', '[西瓜]', '/static/emoji/Expression_57.png'],
    '[啤酒]': ['啤酒', '[啤酒]', '/static/emoji/Expression_58.png'],
    '[篮球]': ['篮球', '[篮球]', '/static/emoji/Expression_59.png'],
    '[乒乓]': ['乒乓', '[乒乓]', '/static/emoji/Expression_60.png'],
    '[咖啡]': ['咖啡', '[咖啡]', '/static/emoji/Expression_61.png'],
    '[米饭]': ['米饭', '[米饭]', '/static/emoji/Expression_62.png'],
    '[猪头]': ['猪头', '[猪头]', '/static/emoji/Expression_63.png'],
    '[玫瑰]': ['玫瑰', '[玫瑰]', '/static/emoji/Expression_64.png'],
    '[凋谢]': ['凋谢', '[凋谢]', '/static/emoji/Expression_65.png'],
    '[嘴唇]': ['嘴唇', '[嘴唇]', '/static/emoji/Expression_66.png'],
    '[爱心]': ['爱心', '[爱心]', '/static/emoji/Expression_67.png'],
    '[心碎]': ['心碎', '[心碎]', '/static/emoji/Expression_68.png'],
    '[蛋糕]': ['蛋糕', '[蛋糕]', '/static/emoji/Expression_69.png'],
    '[闪电]': ['闪电', '[闪电]', '/static/emoji/Expression_70.png'],
    '[炸弹]': ['炸弹', '[炸弹]', '/static/emoji/Expression_71.png'],
    '[刀]': ['刀', '[刀]', '/static/emoji/Expression_72.png'],
    '[足球]': ['足球', '[足球]', '/static/emoji/Expression_73.png'],
    '[瓢虫]': ['瓢虫', '[瓢虫]', '/static/emoji/Expression_74.png'],
    '[便便]': ['便便', '[便便]', '/static/emoji/Expression_75.png'],
    '[月亮]': ['月亮', '[月亮]', '/static/emoji/Expression_76.png'],
    '[太阳]': ['太阳', '[太阳]', '/static/emoji/Expression_77.png'],
    '[礼物]': ['礼物', '[礼物]', '/static/emoji/Expression_78.png'],
    '[拥抱]': ['拥抱', '[拥抱]', '/static/emoji/Expression_79.png'],
    '[强]': ['强', '[强]', '/static/emoji/Expression_80.png'],
    '[弱]': ['弱', '[弱]', '/static/emoji/Expression_81.png'],
    '[握手]': ['握手', '[握手]', '/static/emoji/Expression_82.png'],
    '[胜利]': ['胜利', '[胜利]', '/static/emoji/Expression_83.png'],
    '[抱拳]': ['抱拳', '[抱拳]', '/static/emoji/Expression_84.png'],
    '[勾引]': ['勾引', '[勾引]', '/static/emoji/Expression_85.png'],
    '[拳头]': ['拳头', '[拳头]', '/static/emoji/Expression_86.png'],
    '[差劲]': ['差劲', '[差劲]', '/static/emoji/Expression_87.png'],
    '[爱你]': ['爱你', '[爱你]', '/static/emoji/Expression_88.png'],
    '[NO]': ['NO', '[NO]', '/static/emoji/Expression_89.png'],
    '[OK]': ['OK', '[OK]', '/static/emoji/Expression_90.png'],
    '[爱情]': ['爱情', '[爱情]', '/static/emoji/Expression_91.png'],
    '[飞吻]': ['飞吻', '[飞吻]', '/static/emoji/Expression_92.png'],
    '[跳跳]': ['跳跳', '[跳跳]', '/static/emoji/Expression_93.png'],
    '[发抖]': ['发抖', '[发抖]', '/static/emoji/Expression_94.png'],
    '[怄火]': ['怄火', '[怄火]', '/static/emoji/Expression_95.png'],
    '[转圈]': ['转圈', '[转圈]', '/static/emoji/Expression_96.png'],
    '[磕头]': ['磕头', '[磕头]', '/static/emoji/Expression_97.png'],
    '[回头]': ['回头', '[回头]', '/static/emoji/Expression_98.png'],
    '[跳绳]': ['跳绳', '[跳绳]', '/static/emoji/Expression_99.png'],
    '[投降]': ['投降', '[投降]', '/static/emoji/Expression_100.png'],
    '[激动]': ['激动', '[激动]', '/static/emoji/Expression_101.png'],
    '[乱舞]': ['乱舞', '[乱舞]', '/static/emoji/Expression_102.png'],
    '[献吻]': ['献吻', '[献吻]', '/static/emoji/Expression_103.png'],
    '[左太极]': ['左太极', '[左太极]', '/static/emoji/Expression_104.png'],
    '[右太极]': ['右太极', '[右太极]', '/static/emoji/Expression_105.png'],
    '[奸笑]': ['奸笑', '[奸笑]', '/static/emoji/Expression_106.png'],
    '[嘿哈]': ['嘿哈', '[嘿哈]', '/static/emoji/Expression_107.png'],
    '[捂脸]': ['捂脸', '[捂脸]', '/static/emoji/Expression_108.png'],
    '[机智]': ['机智', '[机智]', '/static/emoji/Expression_109.png'],
    '[茶]': ['茶', '[茶]', '/static/emoji/Expression_110.png'],
    '[红包]': ['红包', '[红包]', '/static/emoji/Expression_111.png'],
    '[耶]': ['耶', '[耶]', '/static/emoji/Expression_113.png'],
    '[皱眉]': ['皱眉', '[皱眉]', '/static/emoji/Expression_114.png'],
};
